199 über unterstunden übertrag
ClockGU/clock-backend pull request #206
Opened 2022-07-04 12:29 UTC by SoerenGrieger

Für die maximal übertragbare Arbeitszeit habe ich nur den Carryover auf maximal 50% der Debit Worktime begrenzt.

Folgende Szenarien sollte das abdecken:

- [ ] Ein Monat ohne Übertrag aus dem Vormonat mit ca 160% Arbeitszeit hat auf dem finalen Stundenzettel nur einen Übertrag von 50% der vereinbarten Arbeitszeit.
- [ ] Ein Monat mit einem Übertrag aus dem Vormonat von ca. 50% der vereinbarten Arbeitszeit kann bei einer Arbeitszeit in diesem Monat von ca. 140% trotzdem nur 50% der vereinbarten Arbeitszeit übertragen.

Frage @chgad : bei mir habe ich bei der Übersicht zum generieren der Stundenzettel noch die Angabe von Übertrag auch größer als 150%, das liegt aber daran, dass deine PRs noch nicht durch sind im Frontend, richtig?

@sheepyhollow ich hatte mit Christian grade besprochen, dass wir im Backend nicht überprüfen, ob jmd zu wenig arbeitet ( < 80% der vereinbarten Arbeitszeit). Zumindest nicht anpassen, wie wir es bei zu viel Arbeitsstunden über 150% machen können. Das einzigste was wir machen könnten, wäre den Import zu verbieten backendseitig, solange nicht min 80% der Arbeitszeit erbracht worden sind?! Aber das fände ich irgendwie Nutzerunfreundlich..

2022-07-04 14:17 UTC, chgad commented
> @sheepyhollow ich hatte mit Christian grade besprochen, dass wir im Backend nicht überprüfen, ob jmd zu wenig arbeitet ( < 80% der vereinbarten Arbeitszeit). Zumindest nicht anpassen, wie wir es bei zu viel Arbeitsstunden über 150% machen können. Das einzigste was wir machen könnten, wäre den Import zu verbieten backendseitig, solange nicht min 80% der Arbeitszeit erbracht worden sind?! Aber das fände ich irgendwie Nutzerunfreundlich..

Nein wir hatten gesagt, dass wir es nicht verbieten. Aber Kappen müssen wir auch auf die maxmial -20% Übertrag.

2022-07-04 14:18 UTC, chgad commented
> Frage @chgad : bei mir habe ich bei der Übersicht zum generieren der Stundenzettel noch die Angabe von Übertrag auch größer als 150%, das liegt aber daran, dass deine PRs noch nicht durch sind im Frontend, richtig?

Ja die sind noch alle offen und folglich nicht gemergt.

2022-07-04 19:08 UTC, sheepyhollow commented
Äh... ist das jetzt noch Input von mir benötigt? Im Zweifel was @chgad sagt...

2022-07-05 06:55 UTC, SoerenGrieger commented
> > @sheepyhollow ich hatte mit Christian grade besprochen, dass wir im Backend nicht überprüfen, ob jmd zu wenig arbeitet ( < 80% der vereinbarten Arbeitszeit). Zumindest nicht anpassen, wie wir es bei zu viel Arbeitsstunden über 150% machen können. Das einzigste was wir machen könnten, wäre den Import zu verbieten backendseitig, solange nicht min 80% der Arbeitszeit erbracht worden sind?! Aber das fände ich irgendwie Nutzerunfreundlich..
> 
> Nein wir hatten gesagt, dass wir es nicht verbieten. Aber Kappen müssen wir auch auf die maxmial -20% Übertrag.

Ich verstehe das ehrlich gesagt nicht, wie ich eine zu geringe Arbeitszeit kappen soll.

Folgendes Beispiel:
Ein User hat 80h Debit Worktime im Monat. Davon arbeitet er aber ein einem Monat nur 10h und hat einen Übertrag vom Vormonat von 5h. Abschließend genereiert der User einen Stundenzettel anhand des bisherigen Release mit 15h geleisteter Arbeit, daraus resultieren 65h Unterstunden. Im Report taucht demnach ein Übertrag von -65h auf, bzw -81,25 % Übertrag!
Nach der Vorgabe "maximal -20% Übertrag" hieße das jetzt was für den User bzw Report?
Wo wollen wir da was kappen?

2022-07-05 15:48 UTC, sheepyhollow commented
Wenn ich das auf dem [Merkblatt](https://www.uni-frankfurt.de/117033578/Merkblatt_SHK_Stand_01_10_2022.pdf) korrekt verstehe, dann dürfen von den -81,25% aus Deinem Beispiel nur -20% übertragen werden.
D.h. der _Übertrag_ wird gekappt. 

Anders gesagt: Du musst in einem Monat mindestens 80% der Stunden erfüllen und darfst dann 20% im nächsten Monat nachholen.

Daran ist komisch, dass der Arbeitgeber sich ja selbst beduppt. Denn die Stunden verfallen ja dann einfach. Aber das ist wohl so.

2022-07-05 16:21 UTC, chgad commented
Sieh es aus dem Gesichtspunkt des Arbeitsschutzes:

Wenn dein Arbeitgeber zu wenig Arbeit für sich hat, dann darf er nicht unbegrenzt von dir Verlangen daa nachzuholen wenn mehr Arbeit da ist.

2022-07-07 11:44 UTC, SoerenGrieger commented
Beim Stundenzettel bin ich mir nicht sicher wie ich das angeben soll, hab hier mal ein Beispiel kreiert:

![Screenshot from 2022-07-07 13-43-06](https://user-images.githubusercontent.com/50986166/177765521-83fe4b6c-92f8-496d-833b-caf8c14b3794.png)
l

Ist das dann wirklich -10:00h geleistete Arbeitszeit oder wären es nicht eig 2:00h geleistete Arbeitszeit?! Oder wollen wir dort die Netto Arbeitszeit?

2022-07-07 12:05 UTC, sheepyhollow commented
Ja, schon 2:00 geleistete Arbeitszeit. Übertrag Folgemonat ist dann -10:00h.

2022-07-07 12:08 UTC, sheepyhollow commented
passt vom Layout her noch "aus dem Vormonat" und "in den Folgemonat" hin?
Und wie steht Ihr dazu, F/K/U unter der geleisteten Arbeitszeit separat aufzuführen? 
#verliertsichindetails

2022-07-07 12:36 UTC, SoerenGrieger commented
> Ja, schon 2:00 geleistete Arbeitszeit. Übertrag Folgemonat ist dann -10:00h.

Nene, der Übertrag ist schon richtig, es wurden nur 2:00h Arbeit geleistet:
Vereinbarte Arbeitszeit: 60h
geleistete Arbeitszeit: 2h
Carryover aus dem Vormonat: -12h
--> netto Arbeitszeiten von -58h aus diesem und -12h aus dem Vormonat = -70h
minimaler Übertrag von -20% der vereinbarten Arbeitszeit: -12h

> passt vom Layout her noch "aus dem Vormonat" und "in den Folgemonat" hin?

könnte, aber wozu? Übertrag ist doch sehr aussagekräftig

> Und wie steht Ihr dazu, F/K/U unter der geleisteten Arbeitszeit separat aufzuführen?

Warum? Das wäre doch in der Summer von "geleistete Arbeitszeit" inkludiert. Das ist alles was das HR braucht bzw der Chef braucht

> #verliertsichindetails

joa



Ich denke wir müssen uns bei sowas immer klar sein wozu gibt es diesen Stundenzettel:
Im Endeffekt geht es im Punkt "geleistete Arbeitszeit" nach meinem Verständnis darum für HR und Vorgesetzte einfach ersichtlich zu machen, ob der/die/das HiWi mit seiner Arbeitszeit, in Abhängigkeit des Übertrags vom Vormonat, +- im Soll ist.
Von daher würde ich meine eigen Frage damit beantworten, dass das mit den -10:00h schon passt und das hier einfach komisch aussieht, weil es ein Sonderfall ist, der so normalerweise nicht auftreten würde.

2022-07-07 13:39 UTC, sheepyhollow commented
> könnte, aber wozu? Übertrag ist doch sehr aussagekräftig

nur keine schöne Grammatik. 

Jetzt habe ich das mit dem Übertrag aber erst verstanden - habe nicht bedacht, dass 12h gerade 20% von 60h sind.
Also so gesehen stimmt es nach unserer Interpretation - jetzt habe ich das aber mal im Excel-AZK nachgestellt und bekomme Folgendes:

![image](https://user-images.githubusercontent.com/13869236/177787207-c3b4aa22-5b03-4372-bb48-871e5c84c184.png)

Ich denke, es wäre ggf. sinnvoll, nochmal bei Herrn Scharf nachzufragen - bislang ging ich davon aus, dass das Excel die Anforderungen exakt umsetzt, aber diese 20%-Kappung ist nicht drin.

2022-07-16 12:04 UTC, SoerenGrieger commented
Zu vollständigen Dokumentation die Aussage zur Handhabung der Unterstunden:

"[...]Sie haben aber recht, eine Kappung macht keinen Sinn, das Minus sollte voll auflaufen, da es sonst unter den Tisch fällt. Der negative Übertrag muss also im vollen Umfang erfolgen, wie dies bei Primion umgesetzt ist. Eine Kappung erfolgt lediglich bei positivem Zeitguthaben.[...]"

Dementsprechender Umbau ist in Arbeit

2022-07-18 09:57 UTC, SoerenGrieger commented
Finde den Fehler...

![Screenshot from 2022-07-18 11-48-51](https://user-images.githubusercontent.com/50986166/179486755-8b39741a-fab4-4a4d-bd62-d4dce307d6a8.png)

Also die Rücknahme von der Mindestarbeitszeit ist so die eine Sache, auf der anderen Seite muss man die CarryoverWorktime der Vormonate eigentlich über die komplette Vertragszeit betrachten, was bisher so nicht umgesetzt ist. Ich würde die daraus etwas komplizierteren Berechnung gerne übersichtlicher in Methoden des Rport Models packen, aber verrenne mich beim programmieren die ganze Zeit. Die damit einhergehenden Änderungen sind dann nämlich doch sehr tiefgreifend.

2022-07-18 10:05 UTC, chgad commented
Ok, und was mochtest du jetzt tun?

2022-07-21 10:09 UTC, SoerenGrieger commented
so, läuft damit wie gewünscht: 
Arbeitszeiten werden korrekt im Report und in der ReportCard angezeigt, der Carryover wird nur noch im Report Model berechnet und es gibt keine von mir erstellten statischen Mehtoden

2022-08-01 15:02 UTC, SoerenGrieger commented
noch nen kleinen bug gefunden, aber jetzt bin ich zufrieden.
@chgad wenn du vor mir wieder da bist, kannst du ja mal drüber schauen und ggf schließen. Ansonsten würde ich den PR nach meinem Urlaub erfolgreich abschließen wollen.

2022-08-18 09:54 UTC, chgad requested changes

2022-08-18 09:54 UTC, chgad commented on api/models.py
> +    def calculate_carryover(self):
Das könnte ein `property`sein.

2022-08-18 09:54 UTC, chgad commented on api/serializers.py
> +        return obj.worktime
Das ist falsch. `get_net_worktime` ist nicht das gleiche wie `.worktime`.

In worktime ist ja der carryover des vorigen Monats drin. deshalb auch die berechnung.

2022-08-29 11:43 UTC, merged