200 limit taegliche arbeitszeit
ClockGU/clock-backend pull request #209
Opened 2022-07-12 09:28 UTC by SoerenGrieger

Max worktime validation hab ich im serializer für `update` und `create` verschieden umgesetzt, aber in eine statische methode gebaut für den ShiftSerilizer.

2022-07-15 08:40 UTC, SoerenGrieger commented
Checks:

- [ ] Erstellen einer Schicht von 10h möglich.
- [ ] Erstellen einer Schicht von 11h nicht möglich.
- [ ] Ändern einer Schicht von 9h auf 11h nicht möglich.
- [ ] Erstellen einer Schicht von 4h und einer Schicht von 6h möglich.
- [ ] Erstellen einer Schicht von 5h und einer Schicht von 6h nicht möglich.
- [ ] Erstellen einer Schicht von 5h und Ändern einer Schicht von 5h auf 6h nicht möglich.

2022-08-02 08:30 UTC, SoerenGrieger commented
Wie von dir @chgad angeregt habe ich hier nun doch auch auf statische Methoden verzichtet. Bitte noch einmal drüber schauen und ggf. PR abschließen. Ansonsten würde ich auch diesen PR nach meinem Urlaub abschließen.

2022-08-18 10:02 UTC, chgad requested changes

2022-08-18 10:02 UTC, chgad commented on api/serializers.py
> +        self.max_dayworktime_validation(validated_data)
Warum hier?
Das gehört in die `validate()` methode.

2022-08-18 10:02 UTC, chgad commented on api/serializers.py
> +        self.max_dayworktime_validation(validated_data)
Ebenfalls: Warum hier? Das muss in der `validate()` methode aufgerufen werden.

2022-08-30 07:51 UTC, merged