225 serializer validierungen
ClockGU/clock-backend pull request #226
Opened 2022-11-08 12:30 UTC by SoerenGrieger

alle Validierungs-Punkte wie in #225 umgesetzt. Einzig ausstehend ist die Validierung, dass sich over all keine Schichten doppeln können (auch mit anderen Verträgen).

2022-11-11 12:31 UTC, SoerenGrieger commented
closing #227

2022-11-14 12:23 UTC, SoerenGrieger commented
ich glaube wir müssen in diesem Zuge das holidays package upgraden, weil in meinen Test greift der 03. Oktober nicht als Feiertag

2022-11-17 11:10 UTC, SoerenGrieger commented
k, alles umgesetzt, ready for review @chgad

2022-11-22 12:24 UTC, chgad requested changes

2022-11-29 10:30 UTC, chgad commented on api/serializers.py
> +            started__month=started.month,
Hast du auch wirklich `started.date()` benutzt ? Denn das ist 'ne Methode kein attribut/property 🙈

2022-11-29 10:33 UTC, SoerenGrieger commented on api/serializers.py
> +            started__month=started.month,
ich hab `started__date=started.date` genutzt. Muss ich auf `started__date=started.date()` gehen?!

2022-11-29 10:38 UTC, chgad commented on api/serializers.py
> +            started__month=started.month,
Exakt :D

2022-12-01 11:41 UTC, merged