Lizensierung mit GPL
ClockGU/clock-backend pull request #273
Opened 2023-06-12 15:21 UTC by SoerenGrieger

close #211 

Grundsätzlich sollte das Licenze File das Thema abdecken.
Allerdings wird empfohlen (siehe Licenze File ganz unten) in jede File folgenden Text an den Anfang zu setzen:
```
Clock - Master your timesheets
Copyright (C) 2023  Johann Wolfgang Goethe-Universität Frankfurt am Main

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

Wie steht ihr dazu @sheepyhollow und @chgad ?

2023-06-16 14:29 UTC, SoerenGrieger commented
```
How to Apply These Terms to Your New Programs

  If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these terms.

  To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

    Clock - Master your timesheets
    Copyright (C) 2023  Johann Wolfgang Goethe-Universität Frankfurt am Main

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

Also add information on how to contact you by electronic and paper mail.

  If your software can interact with users remotely through a computer
network, you should also make sure that it provides a way for users to
get its source.  For example, if your program is a web application, its
interface could display a "Source" link that leads users to an archive
of the code.  There are many ways you could offer source, and different
solutions will be better for different programs; see section 13 for the
specific requirements.

  You should also get your employer (if you work as a programmer) or school,
if any, to sign a "copyright disclaimer" for the program, if necessary.
For more information on this, and how to apply and follow the GNU AGPL, see
<https://www.gnu.org/licenses/>.
```

2023-06-19 15:40 UTC, sheepyhollow commented
Let's!

2023-07-03 08:09 UTC, sheepyhollow approved these changes
Aus meiner Sicht gut so.

2023-07-07 09:19 UTC, chgad requested changes
Es wurden `import`statements "wegrationalisiert" die einen Sinn an der jeweiligen Stelle hatten.
Ich vermute dass ist auf isort oder black zurückzuführen. Hier müssen wir in den Einstellungen etwas ändern dass es nur `global` imports, die nicht benötigt werden, beseitigt.

2023-07-07 09:19 UTC, chgad commented on api/apps.py
> -        import api.utilities
Warum das? So werden unsere celery tasks nicht discovered.

2023-07-07 09:19 UTC, chgad commented on api/tests/test_base_models.py
> -        from api.models import User
Damit wären die Tests obsolet. Was ist hier passiert?

2023-07-07 09:19 UTC, chgad commented on api/tests/test_base_models.py
> -        from api.models import Contract
Damit wären die Tests obsolet. Was ist hier passiert?

2023-07-07 09:19 UTC, chgad commented on api/tests/test_base_models.py
> -        from api.models import Shift
Damit wären die Tests obsolet. Was ist hier passiert?

2023-07-07 09:19 UTC, chgad commented on api/tests/test_base_models.py
> -        from api.models import ClockedInShift
Damit wären die Tests obsolet. Was ist hier passiert?

2023-07-07 09:19 UTC, chgad commented on api/tests/test_base_models.py
> -        from api.models import Report
Damit wären die Tests obsolet. Was ist hier passiert?

2023-07-07 13:33 UTC, chgad approved these changes
Let's gamble try merge

2023-07-07 14:39 UTC, merged